name: Publish Package to npmjs
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "ShivamRawat0l@users.noreply.github.com"
      - run: git config user.name "ShivamRawat0l"
      - run: npm version minor -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: cat package.json
      - run: git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/ShivamRawat0l/react-native-loader-collection.git" --follow-tags
      - run: git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/ShivamRawat0l/react-native-loader-collection.git" --tags
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn run prepare
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
